const pretest = [
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "What is a dendrite?",
      options: [
        "A part of a cell that extends out of the cell body (soma) and receives inputs from other nerve cells.",
        "A part of a cell that extends out of the cell body (soma) and transmits inputs within the nerve cell. ",
        "A part of a cell that ends in a bulbous axon terminal",
        "The location in between two nerve cells where information is transmitted from one cell to the other.",
      ],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:0,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "What is a synapse?",
      options: ["The point where two nerve cells touch to transmit information.", 
        "A long part of a cell that continues from the cell body (soma) and makes contact with the other nerve cells.", 
        "An opening in the cell membrane, where through electrical charged particles like Na+ and K+ enter and leave the cell.", 
        "The connection between two nerve cells that do not physically touch."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:3,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement regarding the concentration gradient is <u>false?</u>",
      options: ["When charged particles are equally spread across an area, the concentration gradient is equal to zero.", 
        "When charged particles are of a higher concentration in point B than in point A, they will want to spread to the point with higher concentration.", 
        "The higher the concentration gradient between point A and point B, the more charged particles strive for concentration equilibrium.", 
        "The level of concentration gradient for X charged particles is independent of the concentration gradient for Y charged particles."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:1,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement regarding the potential gradient is <u>true</u>?",
      options: ["Negatively charged particles attract to each other.", 
        "The potential gradient exists when positively and negatively charged particles are spread equally.", 
        "If electrically charged particles are spread unevenly across two points, an electrical potential will occur between these two points.", 
        "Positively and negatively charged particles do not affect each other's behaviour. "],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:2,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "What is the electrical potential of a cell membrane when a cell is not activated?",
      options: ["The potential measures -70 mV.", 
        "The potential measures +50 mV.", 
        "The potential measures  0 mV.", 
        "The potential measures -30 mV."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:0,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement regarding the functioning of the sodium-potassium pump is <u>true</u>? <br/>The sodium-potassium pump pumps…",
      options: ["Sodium into and potassium out of the cell.", 
        "Potassium and sodium into the cell.", 
        "Potassium and sodium out of the cell.", 
        "Sodium out of and potassium into the cell."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:3,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement is <u>false</u>?<br/>In a cell that is currently not activated…",
      options: ["K+ channels play a vital role.", 
        "Cl- channels play a vital role.", 
        "The concentration gradient plays a vital role.", 
        "The potential gradient plays a vital role."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:1,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement regarding sodium for a non-activated cell is <u>true</u>?",
      options: ["Sodium is actively pumped into the cell.", 
        "Sodium is actively pumped out of the synaptic cleft.", 
        "Sodium is actively pumped out of the cell.", 
        "Sodium passively flows out of the cell."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:2,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement regarding potassium for a non-activated cell is <u>true</u>?",
      options: ["Potassium is pushed out of the synaptic cleft, thanks to the concentration gradient.", 
        "Potassium is pushed out of the cell, thanks to the concentration gradient.", 
        "Potassium is pushed against the concentration gradient into the synaptic cleft.", 
        "Potassium is pushed against the concentration gradient out of the cell."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:1,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "10.	Which statement is <u>true</u>?<br/>In an inactive synapse…",
      options: ["Potassium passes through the cell membrane in both directions (from the inside of the neuron to the outside and vice versa), while sodium only passes through the membrane from the inside to the outside.", 
        "Sodium passes through the cell membrane in both directions (from the inside tof the cell to the outside and vice versa), while potassium only passes through the membrane from the outside to the inside. ", 
        "Both sodium and potassium pass through the cell membrane in both directions (from the inside to the outside and vice versa). ", 
        "Both sodium and potassium pass through the membrane in only one direction."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:0,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement regarding the permeability of the membrane - for a non-activated cell - is <u>true</u>?",
      options: ["The permeability for sodium is greater than for potassium.", 
        "The permeability for sodium and potassium is equal. ", 
        "The permeability for potassium is greater than for sodium.", 
        "The permeability for sodium and potassium is constantly changing."],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:2,
  },
  {
    type: "jsPsychSurveyMultiChoice",
    questions: {
      prompt: "Which statement regarding potassium is <u>true</u>?",
      options: ["Potassium is being pumped out of the cell by the sodium-potassium pump and flows into the cell through the potassium ion channels.", 
        "Potassium is being pumped out of the cell by the sodium-potassium pump and, at the same time, flows out of the cell through the potassium ion channels.", 
        "Potassium is being pumped into the cell by the sodium-potassium pump and, at the same time, flows into the cell through the potassium ion channels. ", 
        "Potassium is being pumped into the cell by the sodium-potassium pump and flows out of the cell through the potassium ion channels. "],
      required: true,
      horizontal: false,
      button_label: "Next >",
    },
    answer_index:3,
  },
 
];
